services:
  frontend:
    build:
      context: ./front-end/
    ports:
      - "5173:5173"
    volumes:
      - .:/fron-end  # Mount current directory to /app in the container for live updates
    command: npm run dev  # Override command to run in development mode

  backend:
    build:
      context: ./back-end/
    ports:
      - "8000:8000"
    volumes:
      - .:/back-end  # Mount current directory to /app in the container for live updates
