# Use an official Node.js runtime as a base image for the Node.js app
FROM node:22-alpine AS node_app

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm config set registry https://registry.yarnpkg.com && npm install

# Copy the local project files to the working directory
COPY . .

# Expose the port the app runs on
EXPOSE 5173

# Start the app
CMD ["npm", "run", "dev"]

# Stage for Nginx
FROM nginx:alpine AS nginx

# Copy Nginx configuration file
COPY ../nginx.conf /etc/nginx/conf.d/default.conf

# Copy SSL certificates into the container
COPY ./certs/selfsigned.crt /etc/nginx/certs/selfsigned.crt
COPY ./certs/selfsigned.key /etc/nginx/certs/selfsigned.key

# Expose port 443 for HTTPS
EXPOSE 443

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
